name: Build and deploy Node.js app with React frontend to Azure Web App - nasa-project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies for client and server
        run: |
          npm install --prefix server
          npm install --prefix client

      - name: Build React app
        run: npm run build --prefix client

      - name: Copy React build to server
        run: |
          mkdir -p server/public
          cp -r client/build/* server/public/

      - name: Zip server (with React build included) for deployment
        run: zip -r release.zip server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_685B6FF5272D40D2B670F0356850717F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0C6BAFA2FD54328B33080B39CE908CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_249F31FCD8AB4736AB7C3E7AD462CF83 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nasa-project'
          slot-name: 'Production'
          package: ./server
